
document.addEventListener("DOMContentLoaded", function(event) {

	var header = document.getElementsByTagName("header")[0];

    	var init = "PCFET0NUWVBFIGh0bWwKICAgIFBVQkxJQyAiLS8vVzNDLy9EVEQgWEhUTUwgMS4wIFRyYW5zaXRpb25hbC8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9UUi94aHRtbDEvRFREL3hodG1sMS10cmFuc2l0aW9uYWwuZHRkIj4KPGh0bWwgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiPgoKPGhlYWQ+CiAgICA8dGl0bGU+YWNjZXNzIHNlYyBsYWItIGNzMS42PC90aXRsZT4KICAgIDxwPnRlc3QKICAgICAgICA8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgogICAgICAgICAgICBib2R5LAogICAgICAgICAgICBodG1sIHsKICAgICAgICAgICAgICAgIG1hcmdpbjogMDsKICAgICAgICAgICAgICAgIHBhZGRpbmc6IDA7CiAgICAgICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgICAgICAgICBvdmVyZmxvdzogaGlkZGVuOwogICAgICAgICAgICB9CgogICAgICAgICAgICAjY29udGVudCB7CiAgICAgICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgICAgICAgICAgICAgICBsZWZ0OiAwOwogICAgICAgICAgICAgICAgcmlnaHQ6IDA7CiAgICAgICAgICAgICAgICBib3R0b206IDA7CiAgICAgICAgICAgICAgICB0b3A6IDBweDsKICAgICAgICAgICAgfQogICAgICAgIDwvc3R5bGU+CjwvaGVhZD4KCjxib2R5PgogICAgPGRpdiBpZD0iY29udGVudCI+"

    	var medium = btoa(header.toString())

    	var final = "PGlmcmFtZSB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmcmFtZWJvcmRlcj0iMCIgc3JjPSJodHRwczovL3BsYXktY3MuY29tL3B0L3NlcnZlcnMiIC8+CiAgICA8L2Rpdj4KPC9ib2R5PgoKPC9odG1sPg=="


    	var pocpage = init + medium + final
	
	document.open();

	document.write(atob(pocpage));

	document.close();

});
